### ISSUE TITLE
Add translations folder 

### ISSUE THREAD

**Issue by alessiobenvenuti** [MichaelCurrin/learn-to-code#24]
Hi, @MichaelCurrin, why not try adding a translation folder to your project to keep everything well organized?

**Comment by MichaelCurrin** [comment]
Sure. Yes I have been thinking how to do it that is inline with Docsify / Jekyll multi language. I'll make a change soon.

**Comment by alessiobenvenuti** [comment]
@MichaelCurrin , Great! Thanks for the reply!

**Comment by MichaelCurrin** [comment]
I've made the changes in PR #27. Let me know if you think of any improvements to the layout before I merge.

**Comment by MichaelCurrin** [comment]
@all-contributors please add @alessiobenvenuti for translations and fixes

**Comment by MichaelCurrin** [comment]
Trying out a bot! :) https://allcontributors.org/docs/en/bot/usage
